# Generated by Django 4.2.9 on 2025-07-25 20:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStats',
            fields=[
                ('article_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('total_reads', models.PositiveIntegerField(default=0)),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('read_count', models.PositiveIntegerField(default=1)),
                ('last_read', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_stats.articlestats')),
            ],
            options={
                'unique_together': {('article', 'user_id')},
            },
        ),
    ]
